name: motorappka
description: "Unofficial app for Motor Lublin fans."
publish_to: 'none' 

version: 0.0.1+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.2.0
  easy_localization: ^3.0.7
  iconic: ^0.1.0
  ionicons: ^0.2.2
  community_material_icon: ^5.9.55
  url_launcher: ^6.3.0
  flutter_octicons: ^0.43.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/ 

flutter_gen:
  output: lib/gen/ 