name: motorappka
description: "Unofficial app for Motor Lublin fans."
publish_to: 'none' 

version: 0.2.1+3

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: 12.1.3
  easy_localization: ^3.0.7
  iconic: ^0.1.0
  ionicons: ^0.2.2
  community_material_icon: ^5.9.55
  url_launcher: ^6.3.0
  flutter_octicons: ^0.43.0
  animated_flip_counter: ^0.3.4
  freezed: ^2.5.2
  freezed_annotation: ^2.4.2
  json_annotation: ^4.9.0
  dio: ^5.5.0+1
  analyzer: ^6.4.1
  flutter_bloc: ^8.1.6
  pretty_dio_logger: ^1.3.1
  carousel_slider: ^4.2.1
  carousel_indicator: ^1.0.6
  dart_date: ^1.3.3
  webview_flutter: ^4.8.0
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  flutter_inappwebview: ^5.8.0
  hydrated_bloc: ^9.1.5
  simple_barcode_scanner: ^0.1.1
  path_provider: ^2.1.3
  barcode_widget: ^2.0.4
  floating_draggable_widget: ^2.1.5
  sugar: ^2.4.1
  time_machine: ^0.9.17
  timezone: ^0.9.4
  wheel_picker: ^0.0.5
  wheel_chooser: ^1.1.2
  dotted_border: ^2.1.0
  firebase_core: ^3.2.0
  package_info_plus: ^8.0.0
  easy_dynamic_theme: ^2.3.1
  double_back_to_close_app: 2.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/ 
    - assets/fonts/
    - assets/timezone/
  
  fonts: 
    - family: Anton
      fonts:
        - asset: assets/fonts/anton.ttf

flutter_gen:
  output: lib/gen/ 

flutter_launcher_icons:
  andoird: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"
  image_path_android: "assets/images/app_icon.png"
  image_path_ios: "assets/images/app_icon.png"
  adaptive_icon_background: "#2a4899"
  adaptive_icon_foreground: "assets/images/app_icon.png"