name: motorappka
description: "Unofficial app for Motor Lublin fans."
publish_to: 'none' 

version: 0.0.1+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.2.0
  easy_localization: ^3.0.7
  iconic: ^0.1.0
  ionicons: ^0.2.2
  community_material_icon: ^5.9.55
  url_launcher: ^6.3.0
  flutter_octicons: ^0.43.0
  animated_flip_counter: ^0.3.4
  freezed: ^2.5.2
  freezed_annotation: ^2.4.2
  json_annotation: ^4.9.0
  dio: ^5.5.0+1
  analyzer: ^6.4.1
  flutter_bloc: ^8.1.6
  pretty_dio_logger: ^1.3.1
  carousel_slider: ^4.2.1
  carousel_indicator: ^1.0.6
  dart_date: ^1.3.3
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/ 
    - assets/fonts/
  
  fonts: 
    - family: Anton
      fonts:
        - asset: assets/fonts/anton.ttf

flutter_gen:
  output: lib/gen/ 